name: Scheduled JMeter Test

on:
  workflow_dispatch:

  schedule:
    - cron: '*/30 * * * *'

jobs:

  jmeter-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz

      - name: Run JMeter Test
        run: |
          apache-jmeter-5.6.3/bin/jmeter -n -t first.jmx -l results.jtl

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
